name: techscout
recipe: drupal10
config:
  webroot: web

services:
  appserver:
    type: php:8.2
    xdebug: true
    port: 80

  database:
    type: mysql
    creds:
      user: techrootscout
      password: kfTkUcJFstoVJ
      database: techscout

  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database

  varnish:
    type: varnish:6.0
    backends:
      - appserver
    config:
      vcl: config/varnish/default.vcl

tooling:
  drush:
    service: appserver
    cmd: "vendor/bin/drush"
  phpunit:
    service: appserver
    description: Run PHPUnit tests.
    cmd: "vendor/bin/phpunit"
